### ISSUE TITLE
Question: theoretical compression ratio limit

### ISSUE THREAD

**Issue by marsupialtail** [fast-pack/SIMDCompressionAndIntersection#34]
Dear Prof. Lemire,

I am interested in this compression algorithm for sorted integers. I am curious about what you think are rule-of-thumb rules for theoretical compression ratio limit, and what this library can achieve.

Let's say we have an array like 3, 6, 9, 12 ... which is the case in the example and the ideal case for compression. I see it uses 2 bits per 32-bit int. However when we have an array like 0, rand(), rand() + rand(), rand() + rand() + rand(), this is probably the worst possible case for compression, I see it uses 14 bits per int.

Are there any rules of thumb I can apply for what compression ratio I should expect? Is there a way to do better than 14 bits for random sequence?

Thank you!

**Comment by marsupialtail** [comment]
let's say it is a random number with uniform or normal distribution from 0 to 10k

**Comment by searchivarius** [comment]
@marsupialtail with most lightweight integer encoding schemes the lower bound is the number of bits to encode is equal to the number of binary digits necessary to encode the number. However, this doesn't include the length of the code.

This number, however, is not an absolute theoretical minimum, because it depends on the encoding scheme and statistical properties of the data, e.g., on repetitiveness. If you have a single number repeated gazillion of times, little space is needed.

**Comment by lemire** [comment]
Let me add that by information theoretical arguments, it is a impossible to consistently store sequences of random integers between 0 and N using less than log N bits per integer on average. If you beat this, either you do not use true random integers or you have made a mistake.

In effect, random numbers cannot be compressed… and that’s a tautology because that is one definition of random (cannot be compressed).

**Comment by searchivarius** [comment]
Only if they are independent. If independence isn't there, an easy counter example:
generate a random number in [0, N] then repeat it a random number [1, M] times.
repeat this procedure many times.
Although the numbers are random, this procedure generates  highly compressible sequences when the median number of repetitions is high.
